import { oc } from "@orpc/contract";

import { accountsRouter } from "./contracts/accounts.ts";
import { categoriesRouter } from "./contracts/categories.ts";
import { connectorsRouter } from "./contracts/connectors.ts";
import { healthRoute } from "./contracts/health.ts";
import { rulesRouter } from "./contracts/rules.ts";
import { settingsRouter } from "./contracts/settings.ts";
import { transactionsRouter } from "./contracts/transactions.ts";
import { truelayerRouter } from "./contracts/truelayer.ts";

export const contract = oc.router({
  health: healthRoute,
  truelayer: truelayerRouter,
  accounts: accountsRouter,
  connectors: connectorsRouter,
  settings: settingsRouter,
  transactions: transactionsRouter,
  rules: rulesRouter,
  categories: categoriesRouter,
});

export type Contract = typeof contract;

export {
  AccountNumberSchema,
  AccountProviderSchema,
  AccountSchema,
  AccountTypeSchema,
  AuthLinkResponseSchema,
  BalanceSeriesInputSchema,
  BalanceSeriesPointSchema,
  BalanceSeriesResponseSchema,
  CATEGORY_COLORS,
  CategoryColorSchema,
  CategoryDescriptorSchema,
  CategoryIdSchema,
  CategoryRuleSchema,
  CategorySourceSchema,
  CategorySpendSchema,
  ClearTransactionCategoryInputSchema,
  ClearTransactionCategoryResponseSchema,
  CreateCategoryRuleInputSchema,
  CreateUserCategoryInputSchema,
  DeleteCategoryRuleInputSchema,
  DeleteCategoryRuleResponseSchema,
  DeleteUserCategoryInputSchema,
  DeleteUserCategoryResponseSchema,
  ListCategoriesResponseSchema,
  ListCategoryRulesResponseSchema,
  MerchantRefSchema,
  RuleAmountOperatorSchema,
  RuleConditionGroupSchema,
  RuleConditionSchema,
  RuleMatchersSchema,
  RuleTextOperatorSchema,
  SetTransactionCategoryInputSchema,
  SetTransactionCategoryResponseSchema,
  SpendingCategorySchema,
  UpdateCategoryRuleInputSchema,
  UpdateUserCategoryInputSchema,
  UserCategorySchema,
  ChangePasswordInputSchema,
  ChangePasswordResponseSchema,
  ConsentStatusSchema,
  CurrencyMonthlySummarySchema,
  CurrencySchema,
  DeleteAccountInputSchema,
  DeleteAccountResponseSchema,
  ExchangeCodeInputSchema,
  ExchangeCodeResponseSchema,
  GenerateAuthLinkInputSchema,
  GetAccountsResponseSchema,
  HealthResponseSchema,
  ListTransactionsInputSchema,
  ListTransactionsResponseSchema,
  MonthlySummaryInputSchema,
  MonthlySummaryResponseSchema,
  NotificationPreferencesSchema,
  SaveAccountsInputSchema,
  SaveAccountsResponseSchema,
  SavedTransactionSchema,
  ThemeSchema,
  TrueLayerAccountSchema,
  UpdateAccountInputSchema,
  UpdateAccountResponseSchema,
  UpdateNotificationPreferencesInputSchema,
  UpdateUserPreferencesInputSchema,
  UserPreferencesSchema,
} from "@spark/schema";

export {
  ConnectorManifestSchema,
  CreateConnectorConnectionInputSchema,
  CreateConnectorConnectionResponseSchema,
  DeleteConnectorConnectionInputSchema,
  DeleteConnectorConnectionResponseSchema,
  ListConnectorConnectionsResponseSchema,
  ListConnectorsResponseSchema,
  SyncConnectorConnectionInputSchema,
  SyncConnectorConnectionResponseSchema,
  TestConnectorConnectionInputSchema,
  TestConnectorConnectionResponseSchema,
} from "@spark/connectors";

export type {
  Account,
  ConsentStatusType,
  BalanceSeriesInput,
  BalanceSeriesPoint,
  BalanceSeriesResponse,
  CategoryColor,
  CategoryDescriptor,
  CategoryId,
  CategoryRule,
  CategorySource,
  CategorySpend,
  ClearTransactionCategoryInput,
  ClearTransactionCategoryResponse,
  CreateCategoryRuleInput,
  CreateUserCategoryInput,
  CurrencyMonthlySummary,
  DeleteCategoryRuleInput,
  DeleteCategoryRuleResponse,
  DeleteUserCategoryInput,
  DeleteUserCategoryResponse,
  ListCategoriesResponse,
  ListCategoryRulesResponse,
  ListTransactionsInput,
  ListTransactionsResponse,
  MerchantRef,
  MonthlySummaryInput,
  MonthlySummaryResponse,
  RuleAmountOperator,
  RuleCondition,
  RuleConditionGroup,
  RuleMatchers,
  RuleTextOperator,
  SavedTransaction,
  SetTransactionCategoryInput,
  SetTransactionCategoryResponse,
  SpendingCategory,
  TrueLayerAccount,
  UpdateCategoryRuleInput,
  UpdateUserCategoryInput,
  UserCategory,
} from "@spark/schema";

export type {
  ConnectorManifest,
  CreateConnectorConnectionInput,
  CreateConnectorConnectionResponse,
  DeleteConnectorConnectionInput,
  DeleteConnectorConnectionResponse,
  ListConnectorConnectionsResponse,
  ListConnectorsResponse,
  SyncConnectorConnectionInput,
  SyncConnectorConnectionResponse,
  TestConnectorConnectionInput,
  TestConnectorConnectionResponse,
} from "@spark/connectors";
